apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
spec:
  replicas: 1
  selector:
    app: {{ .Chart.Name }}
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      limits:
        cpu: "{{ .Values.cpu_limit }}"
        memory: "{{ .Values.memory_limit }}"
      requests:
        cpu: "{{ .Values.cpu_request }}"
        memory: "{{ .Values.memory_request }}"
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: "{{ .Values.admin_db_resource_name }}"
        - name: JWT_OIDC_WELL_KNOWN_CONFIG
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_CONFIG
              name: "{{ .Values.formsflow_config_name }}"
        - name: JWT_OIDC_ISSUER
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_ISSUER
              name: "{{ .Values.formsflow_config_name }}"
        - name: JWT_OIDC_AUDIENCE
          valueFrom:
            secretKeyRef:
              key: ADMIN_WEB_CLIENTID
              name: "{{ .Values.formsflow_secret }}"
        - name: JWT_OIDC_CACHING_ENABLED
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_CACHING_ENABLED
              name: "{{ .Values.formsflow_config_name }}"
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_URL
              name: "{{ .Values.formsflow_config_name }}"
        - name: KEYCLOAK_URL_REALM
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_URL_REALM
              name: "{{ .Values.formsflow_config_name }}"
        - name: FORMSFLOW_WEB_URL
          valueFrom:
            configMapKeyRef:
              key: FORMSFLOW_WEB_URL
              name: "{{ .Values.formsflow_config_name }}"
        - name: CAMUNDA_API_URI
          valueFrom:
            configMapKeyRef:
              key: CAMUNDA_API_URI
              name: "{{ .Values.formsflow_config_name }}"
        - name: KEYCLOAK_ADMIN_CLIENT
          valueFrom:
            secretKeyRef:
              key: BPM_CLIENT_ID
              name: "{{ .Values.formsflow_secret }}"
        - name: KEYCLOAK_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              key: BPM_CLIENT_SECRET
              name: "{{ .Values.formsflow_secret }}"
        
        - name: FORMSFLOW_ADMIN_API_CORS_ORIGINS
          value: '*'
        - name: INSIGHT_API_URL
          valueFrom:
            configMapKeyRef:
              key: INSIGHT_API_URL
              name: "{{ .Values.formsflow_config_name }}"
        - name: INSIGHT_API_KEY
          valueFrom:
            secretKeyRef:
              key: REDASH_SECRET_KEY
              name: "{{ .Values.formsflow_analytics_secret }}"
        image: "{{ tpl .Values.image_url . }}:{{ .Values.tag_name }}"
        name: "{{ .Chart.Name }}"
        ports:
        - containerPort: 5000
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
  test: false
