cpu_limit: 200m
cpu_request: 100m 
forms_url: formio-{{ .Release.Namespace }}.apps.devops.aot-technologies.com
formsflow_secret: forms-flow-ai
image_tag: v4.0.6-alpha
# image_url: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}-tools/{{ .Chart.Name }}.build
image_url: formsflow/forms-flow-forms
memory_limit: 1Gi
memory_request: 512Mi
mongodb_secret_name: formio-mongodb
